Models/ErrorViewModel.cs
using System;

namespace rezokoKanriApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/RecipeClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace rezokoKanriApp.Models
{
    public class RecipeClass
    {
        public int RecipeId { get; set; }
        public string RecipeName { get; set; }

    }
}

Models/StorageLocationClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace rezokoKanriApp.Models
{
    public class StorageLocation
    {
        [Key]
        public int LocationId { get; set; }
        public string LocationName { get; set; }

        // [DataType(DataType.Date)]
        // public DateTime ReleaseDate { get; set; }

        // [DataType(DataType.Date)]
        // public DateTime StartDate { get; set; }

        public string Sublocation { get; set; }
    }
}

Models/StoredItemsClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace rezokoKanriApp.Models
{
    public class StoredItemsClass
    {
        [Key]
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string LocationName { get; set; }

        [DataType(DataType.Date)]
        public DateTime ExpireDate { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using rezokoKanriApp.Models;

namespace rezokoKanriApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StoredItemsClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using rezokoKanriApp.Models;

namespace rezokoKanriApp.Controllers
{
    public class StoredItemsClassesController : Controller
    {
        private readonly rezokoKanriAppContext _context;

        public StoredItemsClassesController(rezokoKanriAppContext context)
        {
            _context = context;
        }

        // GET: StoredItemsClasses
        public async Task<IActionResult> Index()
        {
            return View(await _context.StoredItemsClass.ToListAsync());
        }

        // GET: StoredItemsClasses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var storedItemsClass = await _context.StoredItemsClass
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (storedItemsClass == null)
            {
                return NotFound();
            }

            return View(storedItemsClass);
        }

        // GET: StoredItemsClasses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StoredItemsClasses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemId,ItemName,LocationName,ExpireDate")] StoredItemsClass storedItemsClass)
        {
            if (ModelState.IsValid)
            {
                _context.Add(storedItemsClass);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(storedItemsClass);
        }

        // GET: StoredItemsClasses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var storedItemsClass = await _context.StoredItemsClass.FindAsync(id);
            if (storedItemsClass == null)
            {
                return NotFound();
            }
            return View(storedItemsClass);
        }

        // POST: StoredItemsClasses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemId,ItemName,LocationName,ExpireDate")] StoredItemsClass storedItemsClass)
        {
            if (id != storedItemsClass.ItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(storedItemsClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StoredItemsClassExists(storedItemsClass.ItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(storedItemsClass);
        }

        // GET: StoredItemsClasses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var storedItemsClass = await _context.StoredItemsClass
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (storedItemsClass == null)
            {
                return NotFound();
            }

            return View(storedItemsClass);
        }

        // POST: StoredItemsClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var storedItemsClass = await _context.StoredItemsClass.FindAsync(id);
            _context.StoredItemsClass.Remove(storedItemsClass);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StoredItemsClassExists(int id)
        {
            return _context.StoredItemsClass.Any(e => e.ItemId == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <div class="jumbotron">
            <h1>Welcome</h1>
            <p></p>
            <p>Manage your food inventory here</p>
        </div>
        <div class="card-group row">
            <div class="col">
                <div class="card">
                    <a class="card-body bg-primary text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Storage Location</a>
                    <div class="card-footer">Description here</div>
                    </div>
                </div>
            <div class="col">
                <div class="card">
                    <a class="card-body bg-primary text-white" asp-area="" asp-controller="StoredItemsClasses" asp-action="Index">Stored Items</a>
                    <div class="card-footer">Description here</div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <a class="card-body bg-primary text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Food Recipe</a>
                    <div class="card-footer">Description here</div>
                </div>
            </div>
        </div>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Food Inventory Management</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-brand">Food Inventory Management</div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StoredItemsClasses" asp-action="Index">Stored Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Food Inventory Management App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/StoredItemsClasses/Create.cshtml
@model rezokoKanriApp.Models.StoredItemsClass

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>StoredItemsClass</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ItemName" class="control-label"></label>
                <input asp-for="ItemName" class="form-control" />
                <span asp-validation-for="ItemName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationName" class="control-label"></label>
                <input asp-for="LocationName" class="form-control" />
                <span asp-validation-for="LocationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpireDate" class="control-label"></label>
                <input asp-for="ExpireDate" class="form-control" />
                <span asp-validation-for="ExpireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/StoredItemsClasses/Delete.cshtml
@model rezokoKanriApp.Models.StoredItemsClass

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StoredItemsClass</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocationName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocationName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpireDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ItemId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/StoredItemsClasses/Details.cshtml
@model rezokoKanriApp.Models.StoredItemsClass

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>StoredItemsClass</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocationName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocationName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpireDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ItemId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/StoredItemsClasses/Edit.cshtml
@model rezokoKanriApp.Models.StoredItemsClass

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>StoredItemsClass</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ItemId" />
            <div class="form-group">
                <label asp-for="ItemName" class="control-label"></label>
                <input asp-for="ItemName" class="form-control" />
                <span asp-validation-for="ItemName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationName" class="control-label"></label>
                <input asp-for="LocationName" class="form-control" />
                <span asp-validation-for="LocationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpireDate" class="control-label"></label>
                <input asp-for="ExpireDate" class="form-control" />
                <span asp-validation-for="ExpireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/StoredItemsClasses/Index.cshtml
@model IEnumerable<rezokoKanriApp.Models.StoredItemsClass>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ItemName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LocationName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpireDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ItemName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpireDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ItemId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ItemId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ItemId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>